### ISSUE TITLE
Add the way to ignore specific response codes when calculating coverage

### ISSUE THREAD

**Issue by endless-qa** [reqover/reqover-java#3]
**Description:**

Some response codes might be documented in the API specification but are quite difficult or not even possible to cover in functional API tests. For example, response codes 500 (Internal server error) or 503 (Service unavailable). They are usually covered in the integration testing layer where service behaviour is usually mocked and no real calls to a backend service happen.

**Suggested solution:**

It would be nice to have a way to specify what response codes should not be taken into account (ignored) when calculating the final result. A Reqover user that is going to generate a report, should be able to pass these response codes to the command-line tool via command line parameters or through a configuration file, or via environment variables. The response codes to be ignored, should not appear in the final HTML report and should not affect the coverage percentage. For example:

- there is GET /books/{bookId}
- it has the following response codes: 200, 404 and 500
- a user asks to ignore the 500 response code
- and covers response codes 200 and 404 in his tests.

The final coverage for this endpoint then is 100%, since all not-ignored response codes were covered.

**Extra:**

- There should be a way to pass multiple response-codes-to-be-ignored at the same time to the tool.
- Optionally, ignored response codes could be specified somewhere on top of the HTNL report to increase visibility. Actually, if there going to be more configuration parameters in Reqover, all of them would be nice to see in the report.

**Comment by SergeyPirogov** [comment]
Done
