### ISSUE TITLE
Include query parameters in calculating test coverage

### ISSUE THREAD

**Issue by endless-qa** [reqover/reqover-java#4]
**Description:**

Query parameters can be mandatory or optional. In case of mandatory query parameters, they are covered in functional API tests anyway. But in case of optional query parameters, they can be included but also can be easily missed. For example:
- there the `GET /books/{bookId}` endpoint that has optional query parameter `{year}`
- in the tests, the `GET /books/{bookId}` call with different response codes is covered
- however, it does not mean that the `GET /books/{bookId}?year=2022` functionality works. And if this optional parameter is not covered, then we might miss a bug.

**Proposed solution:**

Query parameters should contribute to the test coverage calculation along with the response codes. For example:
- there is the `GET /books/{bookId}` endpoint with 3 response codes (200, 404 and 500) + 1 optional query parameter (year)
- each of them equally contributes to the endpoint's coverage: code 200 (25%), code 404 (25%), code 500 (25%), year (25%).
- if all response codes are covered in tests but the optional year parameter is not, then endpoint's coverage is 75%.

Extra note:

In case of **mandatory** query parameters, they must be included into a backend call anyway and, hence, will be covered anyway. So, I'd propose to treat them like mandatory path parameters (for example, `{bookId}` from the above-mentioned `GET /books/{bookId}`  example).

**Comment by SergeyPirogov** [comment]
Added in v0.6.8
